"""Add technical columns

Revision ID: 0217fc08699c
Revises: 334b2cf4ddd3
Create Date: 2026-09-10 00:16:01.426162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0217fc08699c'
down_revision: Union[str, Sequence[str], None] = '334b2cf4ddd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicals', sa.Column('volume', sa.Float(), nullable=True))
    op.add_column('technicals', sa.Column('ema_10', sa.Float(), nullable=True))
    op.add_column('technicals', sa.Column('ema_20', sa.Float(), nullable=True))
    op.add_column('technicals', sa.Column('sma_50', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicals', 'sma_50')
    op.drop_column('technicals', 'ema_20')
    op.drop_column('technicals', 'ema_10')
    op.drop_column('technicals', 'volume')
    # ### end Alembic commands ###
