"""drop_unused_fundamentals_columns

Revision ID: 334b2cf4ddd3
Revises: d87c58341d57
Create Date: 2026-09-10 00:08:16.118540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334b2cf4ddd3'
down_revision: Union[str, Sequence[str], None] = 'd87c58341d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_candle_symbol_date', 'candles', ['symbol', 'date'])
    op.create_unique_constraint('uq_fundamental_symbol_date', 'fundamentals', ['symbol', 'date'])
    op.drop_column('fundamentals', 'ev_to_ebitda')
    op.drop_column('fundamentals', 'forward_eps')
    op.drop_column('fundamentals', 'fcf_growth_yoy')
    op.drop_column('fundamentals', 'cash_runway')
    op.drop_column('fundamentals', 'gross_margin')
    op.drop_column('fundamentals', 'forward_pe')
    op.drop_column('fundamentals', 'cash_burn_rate')
    op.drop_column('fundamentals', 'short_interest_pct')
    op.drop_column('fundamentals', 'revenue_cagr_5y')
    op.drop_column('fundamentals', 'target_high_price')
    op.drop_column('fundamentals', 'dividend_yield')
    op.drop_column('fundamentals', 'net_income_cagr_5y')
    op.drop_column('fundamentals', 'profit_margin')
    op.drop_column('fundamentals', 'operating_margin')
    op.drop_column('fundamentals', 'de_ratio')
    op.drop_column('fundamentals', 'beta')
    op.drop_column('fundamentals', 'payout_ratio')
    op.drop_column('fundamentals', 'revenue_growth_fwd')
    op.drop_column('fundamentals', 'earnings_growth_fwd')
    op.drop_column('fundamentals', 'ev_to_revenue')
    op.drop_column('fundamentals', 'current_ratio')
    op.drop_column('fundamentals', 'target_mean_price')
    op.create_unique_constraint('uq_technical_symbol_date', 'technicals', ['symbol', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_technical_symbol_date', 'technicals', type_='unique')
    op.add_column('fundamentals', sa.Column('target_mean_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('current_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('ev_to_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('earnings_growth_fwd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('revenue_growth_fwd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('payout_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('beta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('de_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('operating_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('profit_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('net_income_cagr_5y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('dividend_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('target_high_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('revenue_cagr_5y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('short_interest_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('cash_burn_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('forward_pe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('gross_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('cash_runway', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('fcf_growth_yoy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('forward_eps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('ev_to_ebitda', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint('uq_fundamental_symbol_date', 'fundamentals', type_='unique')
    op.drop_constraint('uq_candle_symbol_date', 'candles', type_='unique')
    # ### end Alembic commands ###
