"""Add missing fundamental columns

Revision ID: 3b8972092499
Revises: ca94852fc7da
Create Date: 2026-08-02 12:13:58.551480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8972092499'
down_revision: Union[str, Sequence[str], None] = 'ca94852fc7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamentals', sa.Column('eps', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('forward_eps', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('dividend_yield', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('profit_margin', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('operating_margin', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('gross_margin', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('ev_to_ebitda', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('current_ratio', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('de_ratio', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('payout_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamentals', 'payout_ratio')
    op.drop_column('fundamentals', 'de_ratio')
    op.drop_column('fundamentals', 'current_ratio')
    op.drop_column('fundamentals', 'ev_to_ebitda')
    op.drop_column('fundamentals', 'gross_margin')
    op.drop_column('fundamentals', 'operating_margin')
    op.drop_column('fundamentals', 'profit_margin')
    op.drop_column('fundamentals', 'dividend_yield')
    op.drop_column('fundamentals', 'forward_eps')
    op.drop_column('fundamentals', 'eps')
    # ### end Alembic commands ###
