"""add generated_report_logs

Revision ID: 523e59521fdc
Revises: e7a4b9a7c3c5
Create Date: 2026-07-03 23:09:41.214115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523e59521fdc'
down_revision: Union[str, Sequence[str], None] = 'e7a4b9a7c3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_report_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_report_logs_generated_at'), 'generated_report_logs', ['generated_at'], unique=False)
    op.create_index(op.f('ix_generated_report_logs_id'), 'generated_report_logs', ['id'], unique=False)
    op.create_index(op.f('ix_generated_report_logs_symbol'), 'generated_report_logs', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_report_logs_symbol'), table_name='generated_report_logs')
    op.drop_index(op.f('ix_generated_report_logs_id'), table_name='generated_report_logs')
    op.drop_index(op.f('ix_generated_report_logs_generated_at'), table_name='generated_report_logs')
    op.drop_table('generated_report_logs')
    # ### end Alembic commands ###
