"""Add CompanyProfile and Technical

Revision ID: 54a1709aabfb
Revises: 3b8972092499
Create Date: 2026-09-09 21:00:50.503881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a1709aabfb'
down_revision: Union[str, Sequence[str], None] = '3b8972092499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_company_profiles_symbol'), 'company_profiles', ['symbol'], unique=False)
    op.create_table('technicals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('avg_volume', sa.Float(), nullable=True),
    sa.Column('rvol', sa.Float(), nullable=True),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('performance_1y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_technical_symbol_date')
    )
    op.create_index(op.f('ix_technicals_date'), 'technicals', ['date'], unique=False)
    op.create_index(op.f('ix_technicals_id'), 'technicals', ['id'], unique=False)
    op.create_index(op.f('ix_technicals_symbol'), 'technicals', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technicals_symbol'), table_name='technicals')
    op.drop_index(op.f('ix_technicals_id'), table_name='technicals')
    op.drop_index(op.f('ix_technicals_date'), table_name='technicals')
    op.drop_table('technicals')
    op.drop_index(op.f('ix_company_profiles_symbol'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
