"""Add Watchlist Table

Revision ID: 71f8e81c6375
Revises: efd770bf8991
Create Date: 2026-06-28 01:45:50.682851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f8e81c6375'
down_revision: Union[str, Sequence[str], None] = 'efd770bf8991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_split_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_hard_update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_watchlist_symbol'), 'watchlist', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_symbol'), table_name='watchlist')
    op.drop_table('watchlist')
    # ### end Alembic commands ###
