"""add_option_signal_logs

Revision ID: 977aea9c8892
Revises: 523e59521fdc
Create Date: 2026-07-05 16:26:31.671425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977aea9c8892'
down_revision: Union[str, Sequence[str], None] = '523e59521fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_signal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_signal_logs_generated_at'), 'option_signal_logs', ['generated_at'], unique=False)
    op.create_index(op.f('ix_option_signal_logs_id'), 'option_signal_logs', ['id'], unique=False)
    op.create_index(op.f('ix_option_signal_logs_symbol'), 'option_signal_logs', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_signal_logs_symbol'), table_name='option_signal_logs')
    op.drop_index(op.f('ix_option_signal_logs_id'), table_name='option_signal_logs')
    op.drop_index(op.f('ix_option_signal_logs_generated_at'), table_name='option_signal_logs')
    op.drop_table('option_signal_logs')
    # ### end Alembic commands ###
