"""update_candle_ma

Revision ID: bb84324722d2
Revises: b7c4e1f0a2d9
Create Date: 2026-10-02 23:10:48.057378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb84324722d2'
down_revision: Union[str, Sequence[str], None] = 'b7c4e1f0a2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_scores', 'price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('candles', sa.Column('ema_10', sa.Float(), nullable=True))
    op.add_column('candles', sa.Column('ema_20', sa.Float(), nullable=True))
    op.drop_column('candles', 'sma_20')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('sma_20', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('candles', 'ema_20')
    op.drop_column('candles', 'ema_10')
    op.alter_column('analysis_scores', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
