"""Add ScreenerUniverse and expand Fundamentals

Revision ID: ca94852fc7da
Revises: 977aea9c8892
Create Date: 2026-07-06 00:10:25.963703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca94852fc7da'
down_revision: Union[str, Sequence[str], None] = '977aea9c8892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screener_universe',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('source_index', sa.String(length=50), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_screener_universe_symbol'), 'screener_universe', ['symbol'], unique=False)
    op.add_column('fundamentals', sa.Column('market_cap', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('beta', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('free_cashflow', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('operating_cashflow', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('fcf_growth_yoy', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('net_debt', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('ebitda', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('net_debt_to_ebitda', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('sma_200', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('fundamentals', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('fundamentals', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('fundamentals', sa.Column('performance_1y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamentals', 'performance_1y')
    op.drop_column('fundamentals', 'score')
    op.drop_column('fundamentals', 'industry')
    op.drop_column('fundamentals', 'sector')
    op.drop_column('fundamentals', 'sma_200')
    op.drop_column('fundamentals', 'net_debt_to_ebitda')
    op.drop_column('fundamentals', 'ebitda')
    op.drop_column('fundamentals', 'net_debt')
    op.drop_column('fundamentals', 'fcf_growth_yoy')
    op.drop_column('fundamentals', 'operating_cashflow')
    op.drop_column('fundamentals', 'free_cashflow')
    op.drop_column('fundamentals', 'beta')
    op.drop_column('fundamentals', 'market_cap')
    op.drop_index(op.f('ix_screener_universe_symbol'), table_name='screener_universe')
    op.drop_table('screener_universe')
    # ### end Alembic commands ###
