"""Drop old columns and watchlist

Revision ID: d87c58341d57
Revises: 54a1709aabfb
Create Date: 2026-09-09 21:01:44.850883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd87c58341d57'
down_revision: Union[str, Sequence[str], None] = '54a1709aabfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_symbol'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_column('fundamentals', 'score')
    op.drop_column('fundamentals', 'rsi')
    op.drop_column('fundamentals', 'iv')
    op.drop_column('fundamentals', 'sector')
    op.drop_column('fundamentals', 'industry')
    op.drop_column('fundamentals', 'avg_volume')
    op.drop_column('fundamentals', 'sma_200')
    op.drop_column('fundamentals', 'rvol')
    op.drop_column('fundamentals', 'performance_1y')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamentals', sa.Column('performance_1y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('rvol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('sma_200', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('avg_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('iv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('rsi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('watchlist',
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_split_check_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_hard_update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('symbol', name=op.f('watchlist_pkey'))
    )
    op.create_index(op.f('ix_watchlist_symbol'), 'watchlist', ['symbol'], unique=False)
    # ### end Alembic commands ###
