"""Add JobLog table

Revision ID: e7a4b9a7c3c5
Revises: 71f8e81c6375
Create Date: 2026-06-28 10:52:02.906286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a4b9a7c3c5'
down_revision: Union[str, Sequence[str], None] = '71f8e81c6375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_logs_id'), 'job_logs', ['id'], unique=False)
    op.create_index(op.f('ix_job_logs_level'), 'job_logs', ['level'], unique=False)
    op.create_index(op.f('ix_job_logs_source'), 'job_logs', ['source'], unique=False)
    op.create_index(op.f('ix_job_logs_timestamp'), 'job_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_logs_timestamp'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_source'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_level'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_id'), table_name='job_logs')
    op.drop_table('job_logs')
    # ### end Alembic commands ###
